defaults:
  - files: mnist # Provide default values for the files
  - _self_ # Files preferential to the current directory
paths:
  log: ./runs
  data: ${hydra:runtime.cwd}/../data/raw
params:
  epoch_count: 20
  lr: 5e-5
  batch_size: 128
